In [4]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [7]:
def mae(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
    #print(yt,yp)
    total_error +=abs(yt-yp)
  print("total error ",total_error)
  mae=total_error/ len(y_true)
  print("mae:",mae)
  return mae

In [8]:
mae(y_true,y_predicted)

total error  2.5
mae: 0.5


0.5

In [10]:
np.mean(y_predicted-y_true)

0.1

In [12]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [13]:
np.log([1])

array([0.])

In [15]:
eplison=1e-15

In [17]:
y_predicted_new=[max(i,eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [19]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([  0.        ,   0.        , -34.53877639, -34.53877639,
         0.        ])

In [25]:
def log_loss(y_true, y_predicted):
    epsilon=1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [26]:
log_loss(y_true,y_predicted)

17.2696280766844